language: python
python: "3.7"
dist: xenial
sudo: required
cache:
  directories:
  - $HOME/.cache/pip
env:
  - SECRET_KEY="sep-travis-secret-key" DB_USER="postgres" DB_NAME="sep"

services:
  - postgresql
before_install:
  - cd backend
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database sep;' -U postgres
script:
  - python manage.py test
